Übungskonzept
aul12/PraktischeITSicherheit-Intel-SGX pull request #14
Opened 2020-05-20 10:11 UTC by aul12

2020-05-20 17:14 UTC, Timmifixedit requested changes

2020-05-20 17:14 UTC, Timmifixedit commented on Exercise/Concept/main.tex
> +    For this exercise the students needs to understand the concept of enclaves and which parts of the application
```suggestion
    For this exercise the students need to understand the concept of enclaves and which parts of the application
```

2020-05-20 17:14 UTC, Timmifixedit commented on Exercise/Concept/main.tex
> +    The exercise relies on some different programs, to enable all students to be able
```suggestion
    The exercise relies on different programs. To enable all students to be able
```

2020-05-21 09:28 UTC, Timmifixedit requested changes

2020-05-21 09:28 UTC, Timmifixedit commented on Exercise/Concept/main.tex
> +    needs to be protected by the enclave. To help the students some pointers about the structure of the application
```suggestion
    need to be protected by the enclave. To help the students some pointers about the structure of the application
```

2020-05-21 10:53 UTC, Timmifixedit approved these changes

2020-05-22 00:34 UTC, pmo73 approved these changes

2020-05-22 00:34 UTC, merged