Sgx how attestion
aul12/PraktischeITSicherheit-Intel-SGX pull request #18
Opened 2020-05-24 01:05 UTC by pmo73

2020-05-25 18:50 UTC, aul12 requested changes

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +            \item That the enclave Code isn't tampered
```suggestion
            \item That the enclave code has not been tampered with
```

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item For attestation a report will be generated by enclave, which contains the identity, enclaves measurement and a supplied message from other enclave
```suggestion
        \item For attestation a report will be generated by enclave, which contains the identity, measurement of the enclave and a supplied message from other enclave
```

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item Report is signeencrypted by the enclave with a symmetric key between target enclave and SGX Implementation
signencrypted?

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item Report is signeencrypted by the enclave with a symmetric key between target enclave and SGX Implementation
Implementation klein

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item Report is signeencrypted by the enclave with a symmetric key between target enclave and SGX Implementation
Statt "SGX implementation" "Processor"?

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item Attestation is for a data exchange between 2 enclaves on same CPU or via remote
Was jetzt Data Exchange oder Verify Integrity?

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +                \item Enclave A generates the report for B with MRENCLAVE and send the report back so B can verify with EGETKEY the report
```suggestion
                \item Enclave A generates the report for B with MRENCLAVE and send the report back so B can verify the report using EGETKEY
```

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +                \item Application receives an attestion request from Challenger
```suggestion
                \item Application receives an attestion request from challenger
```
Challenger wurde noch nicht erklärt

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +                \item Report is requested from application
```suggestion
                \item Application requests report
```

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +                \item Challegner receives quote
```suggestion
                \item Challenger receives quote
```

2020-05-25 18:50 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item Enclave retrieves the seal Key using the EGETKEY instruction, which returns a cryptographical key
```suggestion
        \item Enclave retrieves the sealing key using the EGETKEY instruction, which returns a cryptographic key
```

2020-05-26 11:08 UTC, aul12 requested changes

2020-05-26 11:08 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item Attestation is for a verify integrity between 2 enclaves on same CPU or via remote
```suggestion
        \item Attestation is used two verify integrity of enclaves on same CPU or via remote 
```

2020-05-26 11:08 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item Enclave retrieves the sealing Key using the EGETKEY instruction, which returns a cryptographic key
```suggestion
        \item Enclave retrieves the sealing key using the EGETKEY instruction, which returns a cryptographic key
```

2020-05-26 12:26 UTC, aul12 approved these changes

2020-05-26 12:45 UTC, Timmifixedit requested changes

2020-05-26 12:45 UTC, Timmifixedit commented on Lecture/Attestation.tex
> +        \item Enclaves can seal data with MRSIGNER as key, so no other enclave is able to read data
```suggestion
        \item Enclaves can seal data with MRENCLAVE as key, so no other enclave is able to read data
```

2020-05-26 13:09 UTC, Timmifixedit approved these changes

2020-05-26 13:09 UTC, merged