Attestation and Sealing Rework
aul12/PraktischeITSicherheit-Intel-SGX pull request #28
Opened 2020-05-26 20:53 UTC by Timmifixedit

2020-05-26 21:54 UTC, pmo73 reviewed
Was ist mit excerpt gemeint? Was ist das oder Typo??

2020-05-26 21:57 UTC, pmo73 requested changes

2020-05-26 21:57 UTC, pmo73 commented on Lecture/Attestation.tex
> +        \item Enclaves can provide a report containing (excerpt):
Was ist excerpt oder typo?

2020-05-26 21:57 UTC, pmo73 commented on Lecture/Attestation.tex
> +            \item Message Authentication Code (MAC) over all report fields
Kommt da nicht noch die MRENCLAVE von B mit rein? Die wird doch schon benötigt um das ganze wieder zu entschlüsseln und von B zu verifizieren?

2020-05-27 07:19 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item Enclaves can provide a report containing (excerpt):
Ein Excerpt ist ein Auszug, da hier ja nicht alle Teile genannt werden

2020-05-27 07:23 UTC, aul12 approved these changes

2020-05-27 07:23 UTC, aul12 commented on Lecture/Attestation.tex
> +        \item The Report is signed by the QE using the shared secret
```suggestion
        \item Report is signed by the QE using the shared secret
```
oder report klein

2020-05-27 08:06 UTC, Timmifixedit commented on Lecture/Attestation.tex
> +            \item Message Authentication Code (MAC) over all report fields
Nicht dass ich wüsste. Die Authentizität wir über den MAC sichergestellt. Der MAC wird über die Reportfelder berechnet. Allerdings wird dabei noch einerseits das Processor-Secret genutzt, anderseits auch die MRENCLAVE von B. Dadurch kann nur B den MAC reproduzieren.

2020-05-27 09:33 UTC, pmo73 approved these changes

2020-05-27 09:35 UTC, merged