WIP: Der ganze technische Kram
aul12/PraktischeITSicherheit-Intel-SGX pull request #29
Opened 2020-07-12 15:12 UTC by Timmifixedit

Der Rest der Funktionsweise von SGX

2020-07-13 18:36 UTC, aul12 requested changes

2020-07-13 18:36 UTC, aul12 commented on Summary/sections/2_2-EnclaveLifeCycle.tex
> +Once completely initialized, using EENTER and EEXIT, the enclave can be called from untrusted code. Unused enclaves can also be destructed be using EREMOVE. The live cycle of an
Statt enclave can be called vielleicht functions in the enclave can be called?

2020-07-13 18:36 UTC, aul12 commented on Summary/sections/2_2-EnclaveLifeCycle.tex
> +An initialized enclave can be entered using the EENTER instruction. As stated previously this can only be done from user mode. Similarly to a syscall the context of the current
```suggestion
An initialized enclave can be entered using the EENTER instruction. As stated previously this can only be done from user mode. Similarly to a system call the context of the current
```
syscall ist eher so umgangsprachlich

2020-07-13 18:36 UTC, aul12 commented on Summary/sections/2_3-SpecialProcessorFeatures.tex
> +access untrusted memory. Using special instructions the processor modes can be switched. This behaves similarly to syscall when switching from user mode to kernel mode in order
```suggestion
access untrusted memory. Using special instructions the processor modes can be switched. This behaves similarly to system call when switching from user mode to kernel mode in order
```
s.o.

2020-07-13 18:36 UTC, aul12 commented on Summary/sections/2_4-EnclaveSignature.tex
> +from \cite{IntelEnclaveSignature}). The signature contains among other information:
Vielleicht Anführungszeichen um das Zitat, mir ist jetzt nicht klar wo das anfängt

2020-07-13 19:04 UTC, aul12 approved these changes

2020-07-16 13:56 UTC, aul12 requested changes

2020-07-16 13:56 UTC, aul12 commented on Summary/sections/3-Attestation.tex
> +that Intel basically takes the role of a certificate authority. The remote attestation itself mostly relies on the local attestation process described above using an additional
```suggestion
that Intel takes the role of a certificate authority. The remote attestation itself mostly relies on the local attestation process described above using an additional 
```

2020-07-16 13:56 UTC, aul12 commented on Summary/sections/4-Sealing.tex
> +In both cases, the sealing key is obtained by the EGETKEY instruction which has access to the enclave's SECS and the secret stored inside the processor. The key derivation material
```suggestion
In both cases, the sealing key is obtained by the EGETKEY instruction which has access to the enclave's SECS and the secret stored inside the processor. The key derivation information
```
ist etwas weniger bildlich

2020-07-16 18:15 UTC, Timmifixedit commented on Summary/sections/4-Sealing.tex
> +In both cases, the sealing key is obtained by the EGETKEY instruction which has access to the enclave's SECS and the secret stored inside the processor. The key derivation material
Das habe ich aus diesem einen Report, auf dem quasi unsere ganze Arbeit beruht. Da nennen die das auch konsequent so.

2020-07-16 21:11 UTC, aul12 approved these changes

2020-07-17 01:31 UTC, pmo73 approved these changes

2020-07-17 11:04 UTC, merged