WIP: Introduction and motivation
aul12/PraktischeITSicherheit-Intel-SGX pull request #6
Opened 2020-05-12 15:20 UTC by Timmifixedit

2020-05-13 17:29 UTC, Timmifixedit commented
Soo, das sind jetzt mal n paar Einführungsfolien. Gebt mal euren Senf dazu @aul12 @pmo73

2020-05-13 17:50 UTC, aul12 requested changes
- [x] Es wäre gut wenn du ein paar \section s spendieren würdest, dann sieht man die auch im Inhaltsverzeichnis und linls in der Leiste
 - [x] Auf beiden ersten Folien auf denen man das VM Setup sieht ist Passwort 1 und Passwort 2 ziemlich klein
 - [x] Macht es vielleicht Sinn, dass die Punkte auf einer Folie nacheinander erscheinen?
 - [x] Es wäre schön wenn die drei Bilder mit dem VM Setup die gleiche größe hätten, so dass sich der Stack da zwischen den Folien nicht bewegt
 - [x] Groß-Kleinschreibung bei den Überschriften beachten, im englischen gibt es da Title Case, da wird fast alles groß geschrieben
 - [ ] Vielleicht local/remote attestation und data sealing nochmal erklären, ich denke da wird nicht jeder im Kopf haben wie das bei TPMs war

Inhaltlich aber soweit gut

2020-05-13 18:01 UTC, Timmifixedit commented
Bezüglich TPMs, Sealing, usw. Ich hätte gesagt, das sagt man im Vortrag dazu. Aber ich kanns auch explizit draufschreiben. Dann wird die Folie halt recht voll. Oder man bringt es in dem Teil nochmal dran, wos wirklich drum geht, wie Intel sgx funktioniert

2020-05-13 18:22 UTC, Timmifixedit commented
Dass die Bilder sich nicht bewegen, ist glaub ein ziemliches rumgehäcke mit irgendwelchen spaces. Da nur die erste von den drei Folien 2 Stichpunkte hat, ist sind die Bilder leicht unterschiedlich positioniert

2020-05-13 18:40 UTC, Timmifixedit commented
Das mit dem nacheinander Einblenden hab ich mal eingebaut. Ich bin da eignetlich nie so wirklich ein Freund von. Aber vllt isses dann zum Präsentieren besser. Schaus dir mal an...

2020-05-13 18:41 UTC, aul12 commented
> Bezüglich TPMs, Sealing, usw. Ich hätte gesagt, das sagt man im Vortrag dazu. Aber ich kanns auch explizit draufschreiben. Dann wird die Folie halt recht voll. Oder man bringt es in dem Teil nochmal dran, wos wirklich drum geht, wie Intel sgx funktioniert

Ich denke es reicht wenn es gesagt wird. Du kannst mit \pnote auch Notizen einfügen, dann sieht man gleich was du da sagen willst

2020-05-13 18:42 UTC, aul12 commented
> Dass die Bilder sich nicht bewegen, ist glaub ein ziemliches rumgehäcke mit irgendwelchen spaces. Da nur die erste von den drei Folien 2 Stichpunkte hat, ist sind die Bilder leicht unterschiedlich positioniert

Das geht vielleicht wenn du da zwei Spalten nimmst, aber ist jetzt auf jeden Fall nicht mehr so schlimm

2020-05-13 18:44 UTC, aul12 approved these changes

2020-05-16 09:22 UTC, pmo73 approved these changes

2020-05-16 09:22 UTC, merged