Implementierung von E-Voting Anwendung
aul12/PraktischeITSicherheit-Intel-SGX pull request #7
Opened 2020-05-13 09:38 UTC by aul12

2020-05-13 17:45 UTC, Timmifixedit requested changes

2020-05-13 17:45 UTC, Timmifixedit commented on Exercise/server.c
> +		char *response = handle_vote(fd_ae, fd_ea);
Wenn man doppelt wählt, zählt der hier trotzdem weiter. Die Wahl wird halt nicht eingetragen, aber es werden so halt u.U. nicht 3 Votes abgewartet

2020-05-13 17:46 UTC, Timmifixedit commented
Der Rest sieht gut aus. Hat bei mir auch funktioniert, nachdem ich rausgefunden habe, dass man als ID eine Zahl eingeben muss und keinen Namen

2020-05-13 17:51 UTC, aul12 commented on Exercise/server.c
> +		char *response = handle_vote(fd_ae, fd_ea);
Ist bekannt, das ist nur als Proof of Concept, das kann man auch durch ein (quasi beliebiges) anderes Abbruchkriterium ersetzten

2020-05-13 17:52 UTC, aul12 commented
> Der Rest sieht gut aus. Hat bei mir auch funktioniert, nachdem ich rausgefunden habe, dass man als ID eine Zahl eingeben muss und keinen Namen

Ja das ist primär als Proof of Concept und weniger als Musterlösung gedacht. Wenn ich die Aufgaben genau definiert habe baue ich das noch aus

2020-05-13 17:56 UTC, Timmifixedit approved these changes

2020-05-16 09:21 UTC, pmo73 approved these changes

2020-05-16 09:21 UTC, merged