Exercise Sheet
aul12/PraktischeITSicherheit-Intel-SGX pull request #8
Opened 2020-05-14 13:03 UTC by aul12

2020-05-14 20:05 UTC, Timmifixedit requested changes

2020-05-14 20:05 UTC, Timmifixedit commented on Exercise/Sheet/main.tex
> +    Thus the processor requires hardware support for Intel-SGX, which is only part of more recent Intel
```suggestion
    Thus the processor requires hardware support for Intel-SGX, which is only part of recent Intel
```

2020-05-14 20:05 UTC, Timmifixedit commented on Exercise/Sheet/main.tex
> +    processors (6th generation and later). To be able to test SGX applications on devices without an recent
```suggestion
    processors (6th generation and later). To be able to test SGX applications on devices without a recent
```

2020-05-14 20:05 UTC, Timmifixedit commented on Exercise/Sheet/main.tex
> +    Intel processor, there is OpenSGX. OpenSGX is a emulator (based on QEMU), that emulates the features
```suggestion
    Intel processor, one can use OpenSGX. OpenSGX is an emulator (based on QEMU), that emulates the features
```

2020-05-14 20:05 UTC, Timmifixedit commented on Exercise/Sheet/main.tex
> +    an preconfigured virtual machine image to remove the hassle of compiling OpenSGX from source. To use the image
```suggestion
    a preconfigured virtual machine image to remove the hassle of compiling OpenSGX from source. To use the image
```

2020-05-14 20:41 UTC, Timmifixedit approved these changes

2020-05-16 09:20 UTC, pmo73 approved these changes

2020-05-16 09:49 UTC, merged